name: lauwah
favicon: null
layout_spectrum: 0.4516129
typography_spectrum: 0.4408602
title: LauWah@UCCKE
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2E3029'
    - '#FFFFFF'
    - '#ABA59A'
    - '#923732'
    - '#FFE030'
  brandStrength: 1
  lightness: 0.7275985
  saturation: 1
  rhythmicContrast: 0.7580645
purpose: []
