title: Mr. LauWah @ UCCKE
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7078853
  brandStrength: 1
  lightness: 0.8655914
  brandColors:
    - '#A29A88'
    - '#010007'
    - '#B4B3B6'
    - '#FDFDFD'
    - '#6C675C'
  rhythmicContrast: 0.6648746
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: lauwah
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6523297
layout_spectrum: 1
