title: Mr. LauWah @ UCCKE
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7078853
  brandStrength: 0.7885305
  lightness: 0.8655914
  brandColors:
    - '#161827'
    - '#F4F1F2'
    - '#434A5C'
    - '#B3ACA3'
    - '#024CCF'
  rhythmicContrast: 0.6648746
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: lauwah
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6523297
layout_spectrum: 1
