name: lauwah
favicon: null
layout_spectrum: 0.14019651873968542
typography_spectrum: 0.6258846309501678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5570484038908035
  lightness: 0.9180664569139481
  saturation: 0.8712273736018687
  rhythmicContrast: 0.9826590183656663
purpose: []
