title: Mr. LauWah @ UCCKE
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6971326
  brandStrength: 1
  lightness: 0.1362007
  brandColors:
    - '#2E3029'
    - '#FFFFFF'
    - '#ABA59A'
    - '#923732'
    - '#FFE030'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: lauwah
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5358423
layout_spectrum: 1
